### ISSUE TITLE
qira安装好了之后NC连接报错

### ISSUE THREAD

**Issue by isecren** [geohot/qira#211]
我的Ubuntu64位的 NC连接也出现这个问题

xxxx@ubuntu:~$ nc 127.0.0.1 4000 
Traceback (most recent call last): 
File "/home/xxxx/tools/qira-1.3/middleware/qira.py", line 97, in qira_socat.start_bindserver(program, qira_config.SOCAT_PORT, -1, 1, True) 
File "/home/xxxx/tools/qira-1.3/middleware/qira_socat.py", line 58, in start_bindserver program.execqira(["-qirachild", "%d %d %d" % (parent_id, start_cl, run_id)], shouldfork=False) 
File "/home/xxxx/tools/qira-1.3/middleware/qira_program.py", line 393, in execqira os.execvp(eargs[0], eargs) 
File "/home/xxxx/tools/qira-1.3/venv/lib/python2.7/os.py", line 346, in execvp _execvpe(file, args) File "/home/xxxx/tools/qira-1.3/venv/lib/python2.7/os.py", line 370, in _execvpe func(file, *argrest) OSError: [Errno 2] No such file or directory
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor

**Comment by DayJun** [comment]
我也这个毛病，请问有解决办法了吗？

**Comment by DayJun** [comment]
解决了，安装release版本的就可以了

**Comment by arindhamsharma** [comment]
I am also facing the same error. Please kindly help
